// freezeUnsplashPool.js — convert source.unsplash.com search endpoints in unsplashPool.js
// into direct images.unsplash.com CDN URLs by following redirects. This makes the pool "static"
// and avoids runtime redirects/search issues in clients.

const fs = require('fs');
const path = require('path');
const poolPath = path.join(__dirname, 'unsplashPool.js');
(async function(){
  const mod = require('./unsplashPool');
  const POOL = mod.POOL;
  const categories = Object.keys(POOL);
  console.log(`Found ${categories.length} categories in pool`);

  const result = {};

  for (const cat of categories) {
    result[cat] = [];
    for (const url of POOL[cat]) {
      try {
        const res = await fetch(url, { method: 'GET' });
        // final resolved URL (images.unsplash.com/...) — fetch follows redirects
        const final = res.url || url;
        // quick validation
        const ct = res.headers.get('content-type') || '';
        if (!ct.startsWith('image/')) throw new Error('not-an-image');
        result[cat].push(final);
        console.log(`${cat}: OK -> ${final}`);
      } catch (e) {
        console.log(`${cat}: FAILED -> ${url} (${e.message})`);
      }
    }
  }

  // write new pool file (only replace entries that validated)
  const outLines = [
    "// unsplashPool.js — frozen direct image URLs (generated)",
    "// NOTE: this file was autogenerated by freezeUnsplashPool.js",
    "const POOL = {"
  ];

  for (const cat of Object.keys(result)) {
    outLines.push(`  ${JSON.stringify(cat)}: [`);
    for (const u of result[cat]) {
      outLines.push(`    ${JSON.stringify(u)},`);
    }
    outLines.push('  ],\n');
  }

  outLines.push('};\n\nmodule.exports = { POOL, getRandomImageForCategory: (category) => { const arr = POOL[category] || []; if (!arr.length) return POOL.Default[Math.floor(Math.random()*POOL.Default.length)]; return arr[Math.floor(Math.random()*arr.length)]; } };\n');

  fs.writeFileSync(poolPath, outLines.join('\n'));
  console.log('unsplashPool.js updated with validated direct image URLs (where available).');
})();